# Generated by Django 4.2 on 2023-04-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'Browsers',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'GeoLocation',
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('member_code', models.CharField(max_length=255)),
                ('member_details', models.CharField(max_length=255)),
                ('member_u_code', models.CharField(max_length=255)),
                ('member_spec', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Guests',
            },
        ),
        migrations.CreateModel(
            name='IdVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'IdVerification',
            },
        ),
        migrations.CreateModel(
            name='InternetConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'InternetConnection',
            },
        ),
        migrations.CreateModel(
            name='Level1Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
                ('item_u_code', models.CharField(max_length=255)),
                ('item_spec', models.CharField(max_length=255)),
                ('barcode', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Level1Items',
            },
        ),
        migrations.CreateModel(
            name='Level2Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
                ('item_u_code', models.CharField(max_length=255)),
                ('item_spec', models.CharField(max_length=255)),
                ('barcode', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Level2Items',
            },
        ),
        migrations.CreateModel(
            name='Level3Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
                ('item_u_code', models.CharField(max_length=255)),
                ('item_spec', models.CharField(max_length=255)),
                ('barcode', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Level3Items',
            },
        ),
        migrations.CreateModel(
            name='Level4Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
                ('item_u_code', models.CharField(max_length=255)),
                ('item_spec', models.CharField(max_length=255)),
                ('barcode', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Level4Items',
            },
        ),
        migrations.CreateModel(
            name='Level5Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
                ('item_u_code', models.CharField(max_length=255)),
                ('item_spec', models.CharField(max_length=255)),
                ('barcode', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Level5Items',
            },
        ),
        migrations.CreateModel(
            name='LoginType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'LoginType',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'OperatingSystems',
            },
        ),
        migrations.CreateModel(
            name='PasswordStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'PasswordStrength',
            },
        ),
        migrations.CreateModel(
            name='publiclink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('linkcode', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('dateof', models.CharField(blank=True, max_length=255, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('qrcodeid', models.CharField(blank=True, max_length=255, null=True)),
                ('linkstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('productstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('qrpath', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'publiclink',
            },
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('membertype', models.CharField(max_length=255)),
                ('member', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('datatype', models.CharField(max_length=255)),
                ('operationalrights', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('portfolio_name', models.CharField(max_length=255)),
                ('portfolio_code', models.CharField(max_length=255)),
                ('portfolio_details', models.CharField(max_length=255)),
                ('portfolio_u_code', models.CharField(max_length=255)),
                ('portfolio_spec', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Rights',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('level1', models.CharField(max_length=255)),
                ('level2', models.CharField(max_length=255)),
                ('level3', models.CharField(max_length=255)),
                ('level4', models.CharField(max_length=255)),
                ('level5', models.CharField(max_length=255)),
                ('security_layer', models.CharField(max_length=255)),
                ('role_name', models.CharField(max_length=255)),
                ('role_code', models.CharField(max_length=255)),
                ('role_details', models.CharField(max_length=255)),
                ('role_u_code', models.CharField(max_length=255)),
                ('role_spec', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('member_code', models.CharField(max_length=255)),
                ('member_details', models.CharField(max_length=255)),
                ('member_u_code', models.CharField(max_length=255)),
                ('member_spec', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TeamMembers',
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Urls',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('sessionid', models.CharField(max_length=255)),
                ('alldata', models.TextField()),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('userinfo', models.TextField()),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='UserOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('org', models.TextField()),
            ],
            options={
                'db_table': 'UserOrg',
            },
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('portfolio', models.TextField()),
            ],
            options={
                'db_table': 'UserPortfolio',
            },
        ),
    ]
