# Generated by Django 4.2 on 2023-05-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientadminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('portfolio', models.CharField(max_length=255)),
                ('notification', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
    ]
