from django.urls import path
from .views import *

urlpatterns = [
    path('home', Home1, name="home"),
    path('', Home, name="index"),
    path("otherorg", otherorg, name="otherorg"),
    path("otherorg1", otherorg1, name="otherorg1"),
    path('portfolio', portfolio, name="portfolio"),
    path('exportfolio', portfolioUrl, name="exportfolio"),
    path('refresh', Refresh, name="refresh"),
    path('refreshother', RefreshOther, name="refreshother"),
    path('portfolioadd', PortfolioAdd, name="portfolioadd"),
    path("level_name", Levels, name="level_name"),
    path("members", Members, name="members"),
    path("item_name", Items, name="item_name"),
    path("settings", Settings, name="settings"),
    path("endis", En_dis, name="endis"),
    path("memberen", MemEnDis, name="memberen"),
    # path("edit_item",edititems, name="edit_item"),
    path("addroles", AddRoles, name="addroles"),
    path("invitemembers", InviteMembers, name="invitemebers"),
    path("invitelink", InviteLink, name="invitelink"),
    # path("invitesocial",invitesocial,name="invitesocial"),
    # path("addpublic",addpublic,name="addpublic"),
    path('status', StatusChange, name="status"),
    path('checkhome', CheckHome, name="checkhome"),
    path('speed', speedcheck, name="speed"),
    path('logout', Logout, name="logout"),
    path('layers', Layers, name="layers"),
    path('geolocation', GeoSetting, name="geolocation"),
    path("getdevicelayers", get_device_layers, name="getdevicelayers"),
    path("fileupload", fileupload, name="fileupload"),
    path("add_product", add_product, name="add_product"),
    path("update_product", update_product, name="update_product"),
    path("update_payment", update_payment, name="update_payment"),
    path("importmembers", importusers, name="importmembers"),
    path('dismiss_notification/<int:notification_id>/', dismiss_notification, name='dismiss_notification'),

]
