export const roletextid = [
	"roleheadingtext",
	"roleheadingtext_counter",
	"role_subheading_1",
	"role_subheading_2",
	"role_subheading_3",
	"role_subheading_4",
	"role_subheading_5",
	"role_subheading_6",
	"role_subheading_7",
	"role_subheading_8",
	"role_subheading_9",
	"role_subheading_10",
	"role_subheading_11",
	"role_subheading_12",
	"role_subheading_13",
	"role_subheading_14",
	"role_subheading_15",
	"role_subheading_16",
	"role_subheading_17",
	"role_subheading_18",
	"role_subheading_19",
	"role_subheading_20",
	"role_subheading_21",
	"role_subheading_22",
	"role_subheading_23",
	"role_subheading_24",
	"role_subheading_25",
	"role_subheading_26",
	"role_subheading_27",
	
];


export const roleselectid = [
    "roleselect_1",
    "roleselect_2",
    "roleselect_3",
    "roleselect_4",
    "roleselect_5",
    "roleselect_6",
    "roleselect_7",
    "roleselect_8",
    "roleselect_9",
    "roleselect_10",
    "roleselect_11",
    "roleselect_12",
    "roleselect_13",
    "roleselect_14",
    "roleselect_15",
    
]